"""
Milestone 5b — Streamlit interface
The Unofficial Guide: Student Technology Survival Guide

A simple chat-style UI: the student types a technology question, the app
retrieves the most relevant chunks, generates a grounded answer with the Groq
API, and shows the sources it used so the answer can be verified.

Run:  streamlit run app.py
(Requires: `python ingest.py` and `python embed.py` to have been run first,
 and a GROQ_API_KEY in .env.)
"""

from __future__ import annotations

import streamlit as st

from generate import GROQ_MODEL, answer

# A few of the evaluation questions from planning.md, as one-click examples.
EXAMPLE_QUESTIONS = [
    "How do I reset my school password?",
    "How do I connect my laptop to campus Wi-Fi?",
    "How do I enroll in Multi-Factor Authentication (MFA)?",
    "What should I do if I receive a phishing email?",
    "What laptop is recommended for college students?",  # eval Q5 — coverage-gap demo
]

st.set_page_config(page_title="Student Tech Survival Guide", page_icon="🎓")
st.title("🎓 Student Technology Survival Guide")
st.caption(
    "Ask about Wi-Fi, passwords, Microsoft 365, MFA, Canvas, printing, and more. "
    f"Answers are generated by `{GROQ_MODEL}` from indexed campus IT documents."
)

# --- Example-question buttons populate the input box ---
st.write("**Try an example:**")
cols = st.columns(2)
for i, example in enumerate(EXAMPLE_QUESTIONS):
    if cols[i % 2].button(example, use_container_width=True):
        st.session_state["query"] = example

query = st.text_input(
    "Your question",
    key="query",
    placeholder="e.g. Where can I print documents on campus?",
)

if st.button("Ask", type="primary") and query.strip():
    with st.spinner("Searching the guide and generating an answer..."):
        try:
            result = answer(query)
        except RuntimeError as exc:           # missing API key, etc.
            st.error(str(exc))
            st.stop()
        except Exception as exc:              # network / model errors
            st.error(f"Something went wrong: {exc}")
            st.stop()

    st.markdown("### Answer")
    st.markdown(result.text)

    if result.hits:
        # Programmatically guaranteed source list (derived from retrieval,
        # not from the LLM's text) — this is the authoritative attribution.
        st.markdown("### Retrieved from")
        st.markdown("\n".join(f"- {s}" for s in result.sources))

        st.markdown("#### Chunk detail")
        st.caption("The answer was grounded on these retrieved chunks:")
        for h in result.hits:
            with st.expander(
                f"[Source {h.rank}] {h.source_file} "
                f"· chunk {h.chunk_index} · similarity {h.similarity}"
            ):
                st.write(h.text)
